### ISSUE TITLE
The Unbearable Delay

### ISSUE THREAD

**Issue by RohovDmytro** [kotlyar562/react-native-metronome#1]
I am experience a noticable delay between sounds. So the metronome does not play on exact time (or the dalay it to big).

Any suggestions what I can look into? The app I am experience is very basic. Just a play button. Also I've build a production app and released it to google store to see if it will help but no.

Thank you for sharing your code, btw. It is helpful.

**Comment by kotlyar562** [comment]
I know about this problem on some devices, and I tried to solve it in the latest update, but so far I could not. Using soundPool instead of MediaPlayer is all I could optimize
