### ISSUE TITLE
Error: Resource ID #0x0

### ISSUE THREAD

**Issue by DzmitrySakalouski** [kotlyar562/react-native-metronome#2]
Hello.
I've tried to install and launch an example on android, after clicking start I've got error.
![image](https://user-images.githubusercontent.com/55082507/66830490-467be600-ef5e-11e9-92d0-036f137d17ab.png)

**Comment by DzmitrySakalouski** [comment]
Can anybody please help?

**Comment by kotlyar562** [comment]
Hello. Sorry for the long wait. You did not copy sounds
`4. Important! Copy sounds to folder android/app/src/main/java/res/raw`
sounds - https://github.com/kotlyar562/react-native-metronome/tree/master/example/android/app/src/main/res/raw

**Comment by RechieKho** [comment]
instead of copy into android/app/src/main/java/res/raw, I copied to android/app/src/main/res/raw and it works
